### ISSUE TITLE
Missing functionality when using dynamically built files objects. 

### ISSUE THREAD

**Issue by akupiec** [klei/grunt-injector#16]
Because of behavior destFile option, destination path prefix can not be set anymore
for ex. I have app.js file under path: 
/client/app/app.js
but I want to inject it under:
/public/app/app.js

Right now there is ignorePath option with one is equivalent to cwd but I would like to see something like prefixPath as well

``` javascript
options: {
    min: true,
    destFile : 'client/index.jade',
    ignorePath: 'client/',
    prefixPath: 'public/'
},
files: {
    cwd: 'client/',
    src: [
    'app/app.js'
    ]
}
```

P.S. 
I would appreciate example in documentation how to properly use dynamically file building, because is not obvious

**Comment by willpracht** [comment]
+1 for dynamic file building docs.

**Comment by ptitgraig** [comment]
Hello. I would happily recieve a pull request :)
