### ISSUE TITLE
Could you make standalone version of the injector?

### ISSUE THREAD

**Issue by dciccale** [klei/grunt-injector#18]
Hi, this plugin works really well with grunt, but I am not using grunt for one project and would like to have this plugin.

Could you break the code down for having a nodejs module standalone?

If it is too much, I will do it myself borrowing some code from yours if that is ok.

Thank you

**Comment by ptitgraig** [comment]
@dciccale  Please help yourself, this a an open-source project. One published on npm / Github, please let us now so that we can put a link as well to your project (are you planning making a gulp-injector?)

**Comment by dciccale** [comment]
ok, well having it as standalone could help for making a gulp plugin or using it just with the cli.

anyway i am using other approach now, feel free to close the issue. thanks!

**Comment by joakimbeng** [comment]
@dciccale I've been thinking about this myself! Also there's already a gulp plugin for this: gulp-inject. If/when I extract the logic to a standalone module I will start from gulp-inject instead of this plugin, because that shouldn't be that much work.
