### ISSUE TITLE
Bower dependency injection ignores paths

### ISSUE THREAD

**Issue by Brantner** [klei/grunt-injector#19]
By using injection through 'bower.json' the result html will obtain invalid paths to dependencies as injector doesn't cover a case when html is not located in 'bower_components' parent directory

**Comment by BenMGilman** [comment]
+1

My index file is in src/index.html, and I can't get my bower dependencies to be injected with '../bower_components/...'

**Comment by ptitgraig** [comment]
@Brantner @BenMGilman Have you tried with `cwd` to actually change working directory?
```js
files: {
    cwd: 'client/',
    src: [
    'app/app.js'
    ]
}
```
