### ISSUE TITLE
anything_dependencies override the other

### ISSUE THREAD

**Issue by sshishe** [klei/grunt-injector#23]
I am having following order in my gruntFile.js:

``` js
  bower_dependencies: {
   files: {
     'index.html': ['bower.json'],
   }
 },
  local_dependencies: {
    files: {
      'index.html': ['build/**/*.min.js', 'css/**/*.css'],
    }
  }
```

Whatever comes first will be override by the next one. In this case my bower_dependencies in index.html will be replaced by main.css which is caught by local_dependencies.

Any Idea?

**Comment by ptitgraig** [comment]
@sshishe Can you provides us with your HTML as well?
