### ISSUE TITLE
Can't ignore some/one file (js, css)

### ISSUE THREAD

**Issue by thalespf** [klei/grunt-injector#25]
I like to know if the ignorePath is to remove certain file. The ignorePath option not working for that because It generate a script tag empty. Maybe It remove a path in the script tag, but not the tag.

**Comment by joakimbeng** [comment]
If you want to exclude certain files you should use the negative glob pattern (`!`) for that, e.g: `files: ['src/**/*.css', '!src/not/this.css']`.
