### ISSUE TITLE
Intagrating jade and scss into the injector?

### ISSUE THREAD

**Issue by mooror** [klei/grunt-injector#26]
Hello there, I have been reading through your documentation and am very impressed by this grunt plugin. I researched grunt-wiredep also but found that it seemed to lack the power to inject multiple files from the bower package. This was a problem for me as many of my packages have multiple files that are necessary for production. So when I stumbled upon this package I was really hoping that it would be the package to solve my problems. The strange thing I found was that this plugin as far as I am aware depends upon and uses wiredep but doesn't seem to support .jade and .scss injections. I would happily contribute to this project but I lack a place to start. I would appreciate if someone could help get me started or point out an already existing solution.

Thanks in advance,
Mooror

**Comment by ptitgraig** [comment]
@mooror scss and jade are pre-compiled language that are not directly understood by the browser. I'd suggest maybe in your build to first compile scss to css and jade to HTML and in second place to use grunt-injector. Would that be a solution?
