### ISSUE TITLE
It is possible to pass options to wiredep?

### ISSUE THREAD

**Issue by JohnBernardsson** [klei/grunt-injector#30]
Hi, I wonder if there is some way of passing options like "exclude" to wiredep when injecting bower.json dependencies.

Thanks!

**Comment by joakimbeng** [comment]
Yes when #24 has landed.

**Comment by EvilJohnny** [comment]
I ended up ditching Bower.

Probably I am dumb or something, but for all times I tried to find the good use of Bower in a new project, I simply couldn't. I always find project-specific constraints that make me try workarounds to make it work, so I end up loosing more time on workarounds than the time it might save. 

So I am just using grunt-injector. No Bower. So far, so good. No problems :D
