### ISSUE TITLE
Multiple injections of the same type

### ISSUE THREAD

**Issue by duhseekoh** [klei/grunt-injector#33]
I've been using injector for quite a bit now and appreciate the gap its filled in my grunt workflow.

I think there is some flexibility that could be added. My main scenario is... I have a multi page application. I have a bunch of common javascript, then I have page specific javascript. Right now, each page injects all of the javascript into the same injector block. I wrap that injector block with a usemin `build:js` block. It creates one JS file and I'm good to go.

I'd like to be able to have two different files served up, one global js file, and one page specific file. Usemin allows me to specify as many build blocks as I want. It would be great if I could do that with injector as well. Something like:

```
<!-- build:js index.js -->
<!-- injector:js index -->
<!-- endinjector -->
<!-- endbuild -->

<!-- build:js global.js -->
<!-- injector:js global -->
<!-- endinjector -->
<!-- endbuild -->
```

Thoughts?

**Comment by dennisfrank** [comment]
That would be really great. I have the common use case that some scripts have to be placed inside `<head>` and some before `</body>`. 

@duhseekoh Have you found a solution or workaround?

**Comment by duhseekoh** [comment]
Yea, ive stuck to using one injector but use for loops via grunt templating for any other blocks of script tags. Would still prefer multiple js injectors, but it works.

**Comment by dennisfrank** [comment]
@duhseekoh I found the _official_ way (I think):

It should be possible with the [`starttag` option](https://github.com/klei/grunt-injector#optionsstarttag).
